pretrained_base_model_path: '/var/nfs-mount/aniportrait/stable-diffusion-v1-5'
pretrained_vae_path: '/var/nfs-mount/aniportrait/sd-vae-ft-mse'
image_encoder_path: '/var/nfs-mount/aniportrait/image_encoder'

denoising_unet_path: "/var/nfs-mount/aniportrait/denoising_unet.pth"
reference_unet_path: "/var/nfs-mount/aniportrait/reference_unet.pth"
pose_guider_path: "/var/nfs-mount/aniportrait/pose_guider.pth"
motion_module_path: "/var/nfs-mount/aniportrait/motion_module.pth"

audio_inference_config: "./configs/inference/inference_audio.yaml"
inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'